import React from "react";
import Head from "next/head";
import { useCart, getTotalItems } from "context/cart.context";

const Header: React.FC<{ title: string }> = ({ title }) => {
  const { cart } = useCart();
  return (
    <header className="header">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="header-nav">
        <div>
          <h1>App Store</h1>
        </div>
        <ul className="menus">
          <li>Home</li>
          <li>
            <div>
              <span className="total-items">
                {getTotalItems(cart.products)}
              </span>
              🛒
            </div>
          </li>
        </ul>
      </nav>
    </header>
  );
};

export default Header;
